# Data Exploration

This notebook loads and inspects the travel time results and consumer agent data.

In [2]:
import pandas as pd
import os

## Load Parquet Data

Loading the combined travel times final parquet file.

In [3]:
parquet_path = r'C:\Users\sgabalog\Documents\P3\Model\Utility\utility_scores_bulk.parquet'
df_parquet = pd.read_parquet(parquet_path)
print(f"Parquet file loaded: {parquet_path}")
df_parquet.head()

Parquet file loaded: C:\Users\sgabalog\Documents\P3\Model\Utility\utility_scores_bulk.parquet

,household,sex,age_years,nssec8,pwkstat,salary_yearly,id,num_children,household_size,Postcode,...,8176.0,4325.0,1010.0,8852.0,9356.0,1566.0,950.0,288.0,5856.0,97.0
0,0,MALE,74,NEVER,RETIRED,0.00,0,1,3,L33 4YT,...,0.0,0.0,0.017090,0.0,0.029980,0.300799,0.060776,0.256004,0.0,0.397577
1,1,MALE,86,NEVER,RETIRED,0.00,3,0,1,L33 1UW,...,0.0,0.0,0.063546,0.0,0.108370,1.100338,0.220743,0.955087,0.0,1.440193
2,2,FEMALE,71,SMALL,RETIRED,0.00,4,1,2,L33 4YU,...,0.0,0.0,0.049958,0.0,0.078549,0.857126,0.168373,0.784710,0.0,1.093076
3,3,FEMALE,74,LOWER,RETIRED,0.00,6,1,2,L33 1RZ,...,0.0,0.0,0.066237,0.0,0.112698,1.150246,0.230553,1.000081,0.0,1.504516
4,4,FEMALE,43,ROUTINE,EMPLOYEE_PT,9522.24,8,0,1,L33 9TY,...,0.0,0.0,0.081677,0.0,0.139163,1.183803,0.237264,1.024373,0.0,1.529325

In [4]:
df_parquet.head(10000)

,household,sex,age_years,nssec8,pwkstat,salary_yearly,id,num_children,household_size,Postcode,...,8176.0,4325.0,1010.0,8852.0,9356.0,1566.0,950.0,288.0,5856.0,97.0
0,0,MALE,74,NEVER,RETIRED,0.00,0,1,3,L33 4YT,...,0.0,0.0,0.017090,0.0,0.029980,0.300799,0.060776,0.256004,0.0,0.397577
1,1,MALE,86,NEVER,RETIRED,0.00,3,0,1,L33 1UW,...,0.0,0.0,0.063546,0.0,0.108370,1.100338,0.220743,0.955087,0.0,1.440193
2,2,FEMALE,71,SMALL,RETIRED,0.00,4,1,2,L33 4YU,...,0.0,0.0,0.049958,0.0,0.078549,0.857126,0.168373,0.784710,0.0,1.093076
3,3,FEMALE,74,LOWER,RETIRED,0.00,6,1,2,L33 1RZ,...,0.0,0.0,0.066237,0.0,0.112698,1.150246,0.230553,1.000081,0.0,1.504516
4,4,FEMALE,43,ROUTINE,EMPLOYEE_PT,9522.24,8,0,1,L33 9TY,...,0.0,0.0,0.081677,0.0,0.139163,1.183803,0.237264,1.024373,0.0,1.529325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,FEMALE,26,LOWER,EMPLOYEE_FT,36179.25,24451,0,1,L32 9PY,...,0.0,0.0,0.031723,0.0,0.065025,0.486473,0.102397,0.365976,0.0,0.669555
9996,9996,FEMALE,83,ROUTINE,RETIRED,0.00,24452,0,1,L33 8WZ,...,0.0,0.0,0.006836,0.0,0.017346,0.120559,0.026894,0.073403,0.0,0.179153
9997,9997,FEMALE,29,ROUTINE,HOMEMAKER,0.00,24453,0,2,L32 8UL,...,0.0,0.0,0.100393,0.0,0.166027,1.452384,0.288879,1.282127,0.0,1.858627
9998,9998,FEMALE,86,SMALL,RETIRED,0.00,24455,0,1,L33 5YQ,...,0.0,0.0,0.041113,0.0,0.079046,0.614448,0.127116,0.486692,0.0,0.826109
9999,9999,MALE,66,NEVER,RETIRED,0.00,24456,0,1,L32 8RH,...,0.0,0.0,0.021824,0.0,0.042733,0.341530,0.070956,0.267698,0.0,0.464677

In [ ]:
import pandas as pd
import os

# Set the path to the testing directory
test_data_dir = r'C:\Users\sgabalog\Documents\P3\Model\Utility\testing'

# List all parquet files in the folder
files = [f for f in os.listdir(test_data_dir) if f.endswith('.parquet')]

# Multi-load dictionary to hold the dataframes
data = {}

print(f"--- Loading data from {test_data_dir} ---")
for file_name in files:
    key = file_name.replace('.parquet', '')
    path = os.path.join(test_data_dir, file_name)
    
    # Load the dataset
    data[key] = pd.read_parquet(path)
    
    # Print summary of what was loaded
    print(f"\nLoaded '{key}':")
    print(f"  Shape: {data[key].shape}")
    print(f"  Columns: {list(data[key].columns[:5])} ... and {len(data[key].columns)-5} more.")

# Example: Accessing a specific dataframe
df_bulk_trips = data['utility_scores_bulk_with_trips']


df_bulk_trips.head()

--- Loading data from C:\Users\sgabalog\Documents\P3\Model\Utility\testing ---

Loaded 'utility_scores_average':
  Shape: (10000, 805)
  Columns: ['household', 'sex', 'age_years', 'nssec8', 'pwkstat'] ... and 800 more.

Loaded 'utility_scores_bulk':
  Shape: (10000, 805)
  Columns: ['household', 'sex', 'age_years', 'nssec8', 'pwkstat'] ... and 800 more.

Loaded 'utility_scores_bulk_with_trips':
  Shape: (10000, 813)
  Columns: ['household', 'sex', 'age_years', 'nssec8', 'pwkstat'] ... and 808 more.

Loaded 'utility_scores_convenience':
  Shape: (10000, 805)
  Columns: ['household', 'sex', 'age_years', 'nssec8', 'pwkstat'] ... and 800 more.

,household,sex,age_years,nssec8,pwkstat,salary_yearly,id,num_children,household_size,Postcode,...,8176.0_pt,4325.0_pt,1010.0_pt,8852.0_pt,9356.0_pt,1566.0_pt,950.0_pt,288.0_pt,5856.0_pt,97.0_pt
0,0,MALE,74,NEVER,RETIRED,0.00,0,1,3,L33 4YT,...,0.0,0.0,0.016839,0.0,0.022499,0.301598,0.060373,0.260223,0.0,0.398764
1,1,MALE,86,NEVER,RETIRED,0.00,3,0,1,L33 1UW,...,0.0,0.0,0.066132,0.0,0.088608,1.121975,0.223118,0.984825,0.0,1.466225
2,2,FEMALE,71,SMALL,RETIRED,0.00,4,1,2,L33 4YU,...,0.0,0.0,0.049227,0.0,0.058949,0.859404,0.167258,0.797642,0.0,1.096548
3,3,FEMALE,74,LOWER,RETIRED,0.00,6,1,2,L33 1RZ,...,0.0,0.0,0.064686,0.0,0.083835,1.149935,0.228392,1.013877,0.0,1.505056
4,4,FEMALE,43,ROUTINE,EMPLOYEE_PT,9522.24,8,0,1,L33 9TY,...,0.0,0.0,0.081323,0.0,0.114100,1.202381,0.238808,1.053276,0.0,1.553863

In [13]:
import pandas as pd
import os

# Set the path to the testing directory
test_data_dir = r'C:\Users\sgabalog\Documents\P3\Model\Utility\testing'

# List all parquet files in the folder
parquet_files = [f for f in os.listdir(test_data_dir) if f.endswith('.parquet')]

print(f"--- Converting parquet files to CSV in {test_data_dir} ---")

for file_name in parquet_files:
    # Full path to the input parquet
    input_path = os.path.join(test_data_dir, file_name)
    
    # Define output filename (replacing .parquet with .csv)
    output_name = file_name.replace('.parquet', '.csv')
    output_path = os.path.join(test_data_dir, output_name)
    
    # Read the parquet and save as CSV
    try:
        df = pd.read_parquet(input_path)
        df.to_csv(output_path, index=True)
        print(f"  Successfully saved: {output_name} (Rows: {len(df)})")
    except Exception as e:
        print(f"  Error converting {file_name}: {e}")

print("\n--- All conversions complete ---")

--- Converting parquet files to CSV in C:\Users\sgabalog\Documents\P3\Model\Utility\testing ---
  Successfully saved: utility_scores_average.csv (Rows: 10000)
  Successfully saved: utility_scores_bulk.csv (Rows: 10000)
  Successfully saved: utility_scores_bulk_with_trips.csv (Rows: 10000)
  Successfully saved: utility_scores_convenience.csv (Rows: 10000)

--- All conversions complete ---

In [11]:
df_bulk_trips

NameError: name 'df_bulk_trips' is not defined

In [8]:
utility_scores_average

NameError: name 'utility_scores_average' is not defined

## Load CSV Data

Loading the consumer travel with postcode CSV file.

In [3]:
csv_path = r'C:\Users\sgabalog\Documents\P2\Consumer Agents\2NEWhrp_consumers_travel_with_postcode.csv'
# Note: We use low_memory=False to avoid DtypeWarning for large datasets
df_csv = pd.read_csv(csv_path, low_memory=False)
print(f"CSV file loaded: {csv_path}")
df_csv.head()

CSV file loaded: C:\Users\sgabalog\Documents\P2\Consumer Agents\2NEWhrp_consumers_travel_with_postcode.csv

,sex,age_years,nssec8,pwkstat,salary_yearly,id,household,num_children,household_size,Assigned_Postcode_cleaned,Postcode,RC_ID,distance,mode,time_minutes,indicator,indicator_norm
0,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,L33 4YT,L33 4YT,RC_EW_2871,1668.402,1,25.026,0.315,1.000
1,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,L33 4YT,L33 4YT,RC_EW_2873,1736.649,1,26.050,0.300,0.954
2,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,L33 4YT,L33 4YT,RC_EW_2862,2242.778,1,33.642,0.211,0.670
3,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,L33 4YT,L33 4YT,RC_EW_2865,2273.037,1,34.096,0.207,0.656
4,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,L33 4YT,L33 4YT,RC_EW_2871,1668.402,2,4.004,0.396,1.000

In [8]:
import pandas as pd

# 1. Take the first 11 columns (indices 0 through 10)
df_csv = df_csv.iloc[:, :11]

# 2. Remove "col 10" 
# If you mean index 10 (the 11th column):
df_csv = df_csv.drop(df_csv.columns[10], axis=1)

# OR if you meant index 9 (the 10th column), use:
# df_csv = df_csv.drop(df_csv.columns[9], axis=1)

# 3. Remove rows with duplicates in the 'household' column
# This keeps the first occurrence and removes subsequent ones
df_csv = df_csv.drop_duplicates(subset='household')

# Display result
df_csv.head()

,sex,age_years,nssec8,pwkstat,salary_yearly,id,household,num_children,household_size,Assigned_Postcode_cleaned
0,MALE,74,NEVER,RETIRED,0.00,0,0,1,3,L33 4YT
14,MALE,86,NEVER,RETIRED,0.00,3,1,0,1,L33 1UW
31,FEMALE,71,SMALL,RETIRED,0.00,4,2,1,2,L33 4YU
42,FEMALE,74,LOWER,RETIRED,0.00,6,3,1,2,L33 1RZ
56,FEMALE,43,ROUTINE,EMPLOYEE_PT,9522.24,8,4,0,1,L33 9TY

In [11]:
df_csv = df_csv.rename(columns={'Assigned_Postcode_cleaned': 'Postcode'})

In [12]:
df_csv

,sex,age_years,nssec8,pwkstat,salary_yearly,id,household,num_children,household_size,Postcode
0,MALE,74,NEVER,RETIRED,0.000,0,0,1,3,L33 4YT
14,MALE,86,NEVER,RETIRED,0.000,3,1,0,1,L33 1UW
31,FEMALE,71,SMALL,RETIRED,0.000,4,2,1,2,L33 4YU
42,FEMALE,74,LOWER,RETIRED,0.000,6,3,1,2,L33 1RZ
56,FEMALE,43,ROUTINE,EMPLOYEE_PT,9522.240,8,4,0,1,L33 9TY
...,...,...,...,...,...,...,...,...,...,...
27327127,FEMALE,33,ROUTINE,LONG_TERM_SICK,0.000,1525919,656812,0,2,WA7 2RP
27327135,MALE,58,SEMIROUTINE,EMPLOYEE_FT,21312.795,1525921,656813,0,2,WA7 3HX
27327148,FEMALE,59,INTERMEDIATE,EMPLOYEE_FT,42868.547,1525923,656814,0,2,WA7 3EH
27327162,FEMALE,56,SMALL,EMPLOYEE_FT,20794.768,1525925,656815,1,2,WA7 2RT
27327170,MALE,28,LOWER,EMPLOYEE_FT,30697.574,1525927,656816,0,2,WA7 4YJ

In [13]:
merged_df = pd.merge(df_csv, df_parquet, on='Postcode', how='left')
# 2. Check for missing values in the entire dataframe
missing_values = merged_df.isnull().sum()
print("Columns with missing values:")
print(missing_values[missing_values > 0])
# 3. Specifically check if any 'Postcode' from df_csv failed to find a match in df_parquet
# (Check a column that only exists in df_parquet, e.g., 'Travel_Time')
parquet_cols = [c for c in df_parquet.columns if c != 'Postcode']
if parquet_cols:
    missing_matches = merged_df[parquet_cols[0]].isnull().sum()
    print(f"\nRows in df_csv with no matching Postcode in df_parquet: {missing_matches}")
merged_df.head()

Columns with missing values:
pwkstat    1871
dtype: int64

Rows in df_csv with no matching Postcode in df_parquet: 0

,sex,age_years,nssec8,pwkstat,salary_yearly,id,household,num_children,household_size,Postcode,Walk,Drive,PT
0,MALE,74,NEVER,RETIRED,0.00,0,0,1,3,L33 4YT,"{'1000.0': 198.4, '1010.0': 387.77, '1104.0': ...","{'1000.0': 40.65, '1010.0': 76.1, '1104.0': 73...","{'1000.0': 47.85, '1010.0': 84.89, '1104.0': 8..."
1,MALE,86,NEVER,RETIRED,0.00,3,1,0,1,L33 1UW,"{'1000.0': 171.79, '1010.0': 361.16, '1104.0':...","{'1000.0': 37.59, '1010.0': 73.03, '1104.0': 7...","{'1000.0': 40.07, '1010.0': 77.11, '1104.0': 7..."
2,FEMALE,71,SMALL,RETIRED,0.00,4,2,1,2,L33 4YU,"{'1000.0': 186.09, '1010.0': 375.46, '1104.0':...","{'1000.0': 40.68, '1010.0': 76.12, '1104.0': 7...","{'1000.0': 43.3, '1010.0': 80.34, '1104.0': 80..."
3,FEMALE,74,LOWER,RETIRED,0.00,6,3,1,2,L33 1RZ,"{'1000.0': 196.98, '1010.0': 386.35, '1104.0':...","{'1000.0': 40.58, '1010.0': 76.02, '1104.0': 7...","{'1000.0': 48.21, '1010.0': 85.25, '1104.0': 8..."
4,FEMALE,43,ROUTINE,EMPLOYEE_PT,9522.24,8,4,0,1,L33 9TY,"{'1000.0': 159.37, '1010.0': 348.74, '1104.0':...","{'1000.0': 33.73, '1010.0': 69.17, '1104.0': 6...","{'1000.0': 35.63, '1010.0': 72.66, '1104.0': 7..."

In [10]:
# Define your output path
output_path = r'C:\Users\sgabalog\Documents\P3\Model\Utility\test_consumer_agents_bulk_prepared.parquet'

# Save to parquet
merged_df.to_parquet(output_path, index=False)

print(f"File saved successfully to: {output_path}")

NameError: name 'merged_df' is not defined

## Data Info

Check columns and data types.

In [4]:
print("--- Parquet Info ---")
df_parquet.info()
print("\n--- CSV Info ---")
df_csv.info()

--- Parquet Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37735 entries, 0 to 37734
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Postcode  37735 non-null  object
 1   Walk      37735 non-null  object
 2   Drive     37735 non-null  object
 3   PT        37735 non-null  object
dtypes: object(4)
memory usage: 1.2+ MB

--- CSV Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27327180 entries, 0 to 27327179
Data columns (total 17 columns):
 #   Column                     Dtype
---  ------                     -----
 0   sex                        object
 1   age_years                  int64
 2   nssec8                     object
 3   pwkstat                    object
 4   salary_yearly              float64
 5   id                         int64
 6   household                  int64
 7   num_children               int64
 8   household_size             int64
 9   Assigned_Postcode_cleaned  object
 10  Postcode                   object
 11  RC_ID                      object
 12  distance                   float64
 13  mode                       int64
 14  time_minutes               float64
 15  indicator                  float64
 16  indicator_norm             float64
dtypes: float64(5), int64(6), object(6)
memory usage: 3.5+ GB

In [ ]:
print(gdf_retail_counts.columns.tolist())

['fid_original', 'RC_ID', 'Total_POI_', 'H3_cells', 'Dining_and', 'Leisure_Tr', 'Community_', 'category_n', 'centre_typ', 'LocalAutho', 'LocalAut_1', 'LocalAut_2', 'Active', 'Cafe', 'Convenience Store', 'Entertainment', 'Foodstore', 'Personal Service', 'Professional Services', 'Restaurant', 'Retail', 'geometry']

In [4]:
import geopandas as gpd

gpkg_path = r"C:\Users\sgabalog\Documents\P3\Model\Retail Centre Data\retail_centre_type_counts.gpkg"

# Read the "other" layer: 'retail_centre_counts'
gdf_retail_counts = gpd.read_file(gpkg_path, layer='retail_centre_counts')

# Display the first few rows
gdf_retail_counts.head()

# 1. Drop the geometry column to make it a standard DataFrame
df_retail_counts = gdf_retail_counts.drop(columns='geometry')

# 2. Define the output path
parquet_path = r"C:\Users\sgabalog\Documents\P3\Model\Retail Centre Data\retail_centre_counts.parquet"

# 3. Save to Parquet
df_retail_counts.to_parquet(parquet_path, index=False)

print(f"Successfully saved to: {parquet_path}")

Successfully saved to: C:\Users\sgabalog\Documents\P3\Model\Retail Centre Data\retail_centre_counts.parquet

In [5]:
df_retail_counts.columns

Index(['fid_original', 'RC_ID', 'Total_POI_', 'H3_cells', 'Dining_and',
       'Leisure_Tr', 'Community_', 'category_n', 'centre_typ', 'LocalAutho',
       'LocalAut_1', 'LocalAut_2', 'Active', 'Cafe', 'Convenience Store',
       'Entertainment', 'Foodstore', 'Personal Service',
       'Professional Services', 'Restaurant', 'Retail'],
      dtype='object')

In [2]:
import pandas as pd

In [25]:
parquet_path = r"C:\Users\sgabalog\Documents\P3\Model\Utility\utility_scores_convenience.parquet"
df_parquet = pd.read_parquet(parquet_path)
print(f"Parquet file loaded: {parquet_path}")
df_parquet.head()

Parquet file loaded: C:\Users\sgabalog\Documents\P3\Model\Utility\utility_scores_convenience.parquet

,household,sex,age_years,nssec8,pwkstat,salary_yearly,id,num_children,household_size,prob_convenience,...,9283.0,9300.0,9356.0,9455.0,9477.0,950.0,9576.0,9577.0,97.0,979.0
0,0,MALE,74,NEVER,RETIRED,0.00,0,1,3,1.0,...,0.0,0.0,0.221607,0.083891,0.117772,0.123801,0.0,0.0,0.733450,0.022114
1,1,MALE,86,NEVER,RETIRED,0.00,3,0,1,0.0,...,0.0,0.0,0.258580,0.087376,0.115208,0.149029,0.0,0.0,0.872098,0.029090
2,2,FEMALE,71,SMALL,RETIRED,0.00,4,1,2,0.1,...,0.0,0.0,0.251372,0.089973,0.135817,0.149546,0.0,0.0,0.874363,0.031025
3,3,FEMALE,74,LOWER,RETIRED,0.00,6,1,2,0.0,...,0.0,0.0,0.202613,0.076254,0.118434,0.122910,0.0,0.0,0.716775,0.025279
4,4,FEMALE,43,ROUTINE,EMPLOYEE_PT,9522.24,8,0,1,0.0,...,0.0,0.0,0.241256,0.088878,0.124735,0.141509,0.0,0.0,0.843304,0.028156

In [23]:
df_parquet

,sex,age_years,nssec8,pwkstat,salary_yearly,id,household,num_children,household_size,prob_convenience,...,Retail,Cafe,Personal and Professional Services,Restaurant,Entertainment,Total,Duration_Scaled,W_entertainment,W_restaurant,Utility_Score
162,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,1.0,...,1,1,1,1,1,1.000000,0.871108,0.5,0.5,1.689396
67,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,1.0,...,1,1,1,1,1,0.036530,0.945629,0.5,0.5,1.601267
158,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,1.0,...,1,1,0,1,1,0.014840,1.000000,0.5,0.5,1.406003
80,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,1.0,...,1,1,1,0,1,0.030822,0.662084,0.5,0.5,0.915790
35,MALE,74,NEVER,RETIRED,0.0,0,0,1,3,1.0,...,1,1,1,1,1,0.063927,0.838441,0.5,0.5,0.899260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258987,FEMALE,43,NEVER,LONG_TERM_SICK,0.0,2575,999,0,2,0.1,...,1,1,0,0,1,0.009132,0.502591,0.5,0.5,0.000000
258990,FEMALE,43,NEVER,LONG_TERM_SICK,0.0,2575,999,0,2,0.1,...,1,1,0,1,0,0.007991,0.480941,0.5,0.5,0.000000
258991,FEMALE,43,NEVER,LONG_TERM_SICK,0.0,2575,999,0,2,0.1,...,1,1,0,1,1,0.007991,0.406817,0.5,0.5,0.000000
258996,FEMALE,43,NEVER,LONG_TERM_SICK,0.0,2575,999,0,2,0.1,...,0,0,1,0,0,0.000000,0.607686,0.5,0.5,0.000000
258997,FEMALE,43,NEVER,LONG_TERM_SICK,0.0,2575,999,0,2,0.1,...,1,1,0,0,0,0.000000,0.579746,0.5,0.5,0.000000

In [11]:


df_parquet.to_csv(r"C:\Users\sgabalog\Documents\P3\Model\Utility\scores1.csv")

In [ ]:
parquet_path = r'C:\Users\sgabalog\Documents\P3\Model\Utility\consumer_agents.parquet'
df_parquet = pd.read_parquet(parquet_path)
print(f"Parquet file loaded: {parquet_path}")
df_parquet.head()
df_parquet['p_con'] = 1/3
df_parquet['p_bulk'] = 1/3
df_parquet['p_online'] = 1/3
# 2. Add stock_level: 100 * household_size, randomized between 0 and that value
# np.random.uniform(0, 1, size=len(df_parquet)) generates a random multiplier for each row
df_parquet['stock_level'] = np.random.uniform(0, 1, size=len(df_parquet)) * (100 * df_parquet['household_size'])
# 3. Add consumption_rate: randomized between 50 and 100
df_parquet['consumption_rate'] = np.random.uniform(50, 100, size=len(df_parquet))
# 4. Add shopping_threshold: 10 * household_size
df_parquet['shopping_threshold'] = 10 * df_parquet['household_size']



parquet_path = r'Retail Centre Data/retail_centre_type_counts.gpkg'
df_parquet = pd.read_parquet(parquet_path)
print(f"Parquet file loaded: {parquet_path}")
df_parquet.head()
##### ADD CODE HERE TO COMBINE PERSONAL AND PROFESIONAL SERVICES AND REMOVE ACTIVE!!!! also classifiy the columns based on Total_POI_ column, use the counts to make 10 equal groups, call that column Classifca

columns_to_scale = [
    'Foodstore','Convenience Store','Retail','Cafe',
    'Personal and Professional Services','Restaurant','Entertainment'
]

for col in columns_to_scale:
    df[f'{col}_scaled_class'] = df.groupby('Classifica')[col].transform(
        lambda x: (x - x.min()) / (x.max() - x.min())
    )

df

create two new datasets one called consumer_agents_convenience and consumer_agents_bulk
in both add cols which are p_  'Foodstore','Convenience Store','Retail','Cafe',
    'Personal and Professional Services','Restaurant','Entertainment'for each of the categories appearing in retail centres
save all new datasets in utility folder all as parquet